config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  
  root 'stocks#index'
end

app/models/stock.rb
# Stock model
class Stock < ActiveRecord::Base
  validates :stock_name, presence: true, uniqueness: true
  validates :price, numericality: { greater_than: 0 }
  validates :quantity, numericality: { only_integer: true, greater_than: 0 }
  validates :percentage, numericality: { greater_than: 0 }
  validates :years, numericality: { only_integer: true, greater_than: 0 }

  def stock_values
    period = (0..years)
    Hash[period.map { |year| [year, sprintf('%.2f', value_for_year(year))] }]
  end

  private

  def value_for_year(year)
    price * quantity * (1 + percentage / 100)**year
  end
end

app/controllers/application_controller.rb
# Main application controller
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stocks_controller.rb
# Stocks controller
class StocksController < ApplicationController
  def index
    @stocks = Stock.all
  end

  def show
    @title = 'Calculation result'
    @stock = Stock.find params[:id]
  end

  def new
    @title = 'Enter stock details'
    @stock = Stock.new
  end

  def create
    @stock = Stock.new stock_params

    if @stock.save
      redirect_to @stock
    else
      @title = 'Enter stock details'
      render action: :new
    end
  end
  
  def destroy
    Stock.find(params[:id]).destroy
    redirect_to root_path
  end

  private

  def stock_params
    params.require(:stock)
      .permit(:stock_name, :price, :quantity, :percentage, :years)
  end
end

app/helpers/application_helper.rb
# Global helper methods
module ApplicationHelper
  def title
    base_title = 'Stock productivity calculator'
    @title || base_title
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= title
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag '//www.google.com/jsapi', 'chartkick'
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          = link_to 'StockRock', root_path, class: 'navbar-brand'
        
    .container
      = yield

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  .alert.fade.in.alert-danger.alert-dismissable
    %button.close{type: 'button', data: { dismiss: 'alert' }}
      %span{aria: { hidden: 'true' }} &times;
    %ul#error-messages
      - object.errors.full_messages.each do |msg|
        = content_tag :li, msg if msg.is_a?(String)

app/views/stocks/index.html.haml
%h1 Stocks index

%p
  = link_to 'Enter new stock', new_stock_path, class: 'btn btn-primary btn-lg'

- unless @stocks.blank?
  %table.table.table-bordered.table-hover#stocks
    %thead
      %tr
        %th Name
        %th Price
        %th Quantity
        %th Percentage
        %th Years
    %tbody
      - @stocks.each do |stock|
        %tr
          %td= link_to stock.stock_name, stock
          %td= sprintf('%.2f', stock.price)
          %td= stock.quantity
          %td= sprintf('%.2f', stock.percentage)
          %td= stock.years

app/views/stocks/new.html.haml
%h1 New stock

= render 'shared/error_messages', object: @stock

= form_for @stock, html: { class: 'form-horizontal' } do |f|
  .form-group
    = f.label :stock_name, class: 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :stock_name, class: 'form-control', placeholder: 'Example: Company XYZ'
  .form-group
    = f.label :price, class: 'col-sm-2 control-label'
    .col-sm-2
      = f.number_field :price, class: 'form-control', placeholder: 'Example: 42.50', min: 0, step: 'any'
  .form-group
    = f.label :quantity, class: 'col-sm-2 control-label'
    .col-sm-2
      = f.number_field :quantity, class: 'form-control', placeholder: 'Example: 365', min: 1
  .form-group
    = f.label :percentage, class: 'col-sm-2 control-label'
    .col-sm-2
      = f.number_field :percentage, class: 'form-control', placeholder: 'Example: 3.5', min: 0, step: 'any'
  .form-group
    = f.label :years, class: 'col-sm-2 control-label'
    .col-sm-2
      = f.number_field :years, class: 'form-control', placeholder: 'Example: 10', min: 1
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit 'Calculate', class: 'btn btn-success btn-lg'

app/views/stocks/show.html.haml
%p
  = link_to :back, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-chevron-left
    Back
  = link_to @stock, data: {method: :delete, confirm: 'Are you sure?'}, class: 'btn btn-danger' do
    %span.glyphicon.glyphicon-trash
    Delete
%h1= "Stock data for #{@stock.stock_name}"

.row
  .col-sm-3
    %table.table.table-bordered.table-hover#stock-data
      %tr
        %th Stock name
        %td= @stock.stock_name
      %tr
        %th Price
        %td= '%.2f' % @stock.price
      %tr
        %th Quantity
        %td= @stock.quantity
      %tr
        %th Percentage
        %td= '%.2f' % @stock.percentage
      %tr
        %th Years
        %td= @stock.years

  .col-sm-2
    %table.table.table-bordered.table-hover#stock-values
      - @stock.stock_values.each do |row|
        %tr
          %td= row.first
          %td= row.last

  .col-sm-7
    #stock-graph
      = bar_chart @stock.stock_values, discrete: true, height: '600px', library: {title: 'Stock value growth by years', chartArea: {width: '80%', height: '80%'}}